### ISSUE TITLE
"netcvupdate -n -R" keeps stuck (but seems to trigger a reboot)

### ISSUE THREAD

**Issue by M-Reimer** [vdr-projects/libnetceiver#1]
Commanding the NetCeiver to reboot via "netcvupdate" seems to successfully make the server reboot (access shortly after issuing the command is not possible) but the "netcvupdate" command itself is stuck forever. I had to "Ctrl + C" out of it.

Not that critical and unfortunately I won't be able to work on this (don't have a NetCeiver, myself, and if I occasionally meet the friend who has a NetCeiver, I don't want to do long debug sessions).

**Comment by pbiering** [comment]
issuue reproduced, hanging after "SITE exec reboot -d 5", will investigate

**Comment by pbiering** [comment]
`site exec reboot -d 5` has to be pushed to background by the FTP server as otherwise blocking the client. Strangewise `lftp` is not proper supporting "&" (it throws itself - the client - somehow in the background), but found that `tnftp` client is working well. Therefore added support for `tnftp`.

@M-Reimer : please test and review the PR

**Comment by M-Reimer** [comment]
Something is off here... Wasn't "tnftp" the actual client used by Baycom? So the "new default" could be just to have "tnftp" instead of "ftp" and no command line option needed?

http://www.vdr-wiki.de/wiki/index.php/Netceiver#Optionale_Pakete

As far as I know Reel had "tnftp" on their boxes named as just "ftp". That's why the default command name is just "ftp". But basically no Linux distribution uses "tnftp" as their "default command line FTP client". They all name it "tnftp".

**Comment by pbiering** [comment]
good catch, especially as `tnftp` is also mentioned in file on top...

```
* - feed commands into tnftp 
```

added now an autodetection and also extend RPM requirements

**Comment by M-Reimer** [comment]
Is the new command line option "-t" still needed then?

**Comment by pbiering** [comment]
only in case of autodetection fails (see also updated online help)

**Comment by M-Reimer** [comment]
Which FTP client is the "default" then?

**Comment by pbiering** [comment]
have reworked the autodetection now, it expects now as default `tnftp` or `ftp` being the same. Warning message extended. Option `-t` dropped.

**Comment by M-Reimer** [comment]
Nice. Thanks. I will test this as soon as possible. But I will not meet my friend this weekend. So could take a little longer.
